server:
  port: 9001
spring:
  application:
    name: server-provider

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-interval: 10s
        service-name: ${spring.application.name}
        register-health-check: true
        health-check-path: /check
